import React,{useState} from 'react';
import{createRoot}from'react-dom/client';
import{Menu,X,Phone,ArrowUpRight,MapPin,Clock,ChevronDown,Camera,Users,Mail}from'lucide-react';
import'./styles.css';

const tour=[
 ['Lundi soir','Tramelan','Fabien Bike Sàrl','079 369 10 36'],
 ['Mardi midi','Bienne','Swatch SA · devant le musée','079 369 10 36'],
 ['Mardi soir','Corgémont','Place communale','079 369 10 36'],
 ['Mercredi midi','Sonceboz','Shop du Pierre-Pertuis','079 369 10 36'],
 ['Mercredi soir','Péry','Place communale','079 369 10 36'],
 ['Mercredi soir','Grandval',"Fromagerie Au P'tit lait",'079 828 10 36'],
 ['Jeudi soir','Court',"Devant l’Ultra",'079 369 10 36'],
 ['Vendredi soir','Prêles','Milieu du village','079 369 10 36'],
];
const shops=['Fromagerie des Reussilles · 2722 Les Reussilles','Volg · 2608 Courtelary','Shop Dänzer · 2606 Corgémont','Shop Dänzer Frères · 2517 Diesse',"Laiterie Au P’tit Lait · 2745 Grandval",'Agrola TopShop · 2733 Pontenet','Boucherie Carnata Sàrl · 2710 Tavannes','Coopérative Le Nid · 1205 Genève','Suter Viandes SA · 1844 Villeneuve'];
const nav=[['La carte','carte'],['La tournée','tournee'],['Notre savoir-faire','engagement'],['Événements','evenements'],['Pizzas fraîches','fraiches'],['Concours','concours']];

function App(){const[open,setOpen]=useState(false);const[menuOpen,setMenuOpen]=useState(false);const[submitted,setSubmitted]=useState(false);
 const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenuOpen(false)};
 return <>
  <header><button className="brand" onClick={()=>scrollTo({top:0,behavior:'smooth'})}><img src="./images/logo.png"/><span>LA LÉGENDE</span></button><nav>{nav.map(([l,id])=><button key={id} onClick={()=>go(id)}>{l}</button>)}</nav><a className="order small" href="tel:+41793691036"><Phone size={16}/> Commander</a><button className="mobile" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Menu">{menuOpen?<X/>:<Menu/>}</button></header>
  {menuOpen&&<div className="mobileNav">{nav.map(([l,id])=><button key={id} onClick={()=>go(id)}>{l}</button>)}<a href="tel:+41793691036">079 369 10 36</a></div>}
  <main>
   <section className="hero"><div className="eyebrow">Food truck · Jura bernois · Depuis 2019</div><h1>LA PIZZA<br/>QUI DEVIENT<br/><i>LÉGENDE.</i></h1><p>Une pâte maison, des ingrédients choisis avec soin et le feu du four. Retrouvez-nous chaque semaine près de chez vous.</p><div className="actions"><button className="order" onClick={()=>go('tournee')}>Trouver le camion <ArrowUpRight size={18}/></button><button className="ghost" onClick={()=>go('carte')}>Voir la carte</button></div><img className="heroPizza" src="./images/pizza-hero.jpg" alt="Pizza artisanale La Légende"/><div className="scroll">DÉCOUVRIR <span>↓</span></div></section>
   <section className="manifest" id="engagement"><div className="sectionNo">01 / SAVOIR-FAIRE</div><h2>PEU D’ARTIFICE.<br/>BEAUCOUP DE <i>GOÛT.</i></h2><div className="manifestGrid"><p>Notre farine vient directement d’un moulin italien choisi depuis des années par les champions du monde de la pizza.</p><div className="values"><article><b>01</b><h3>PÂTE MAISON</h3><p>Préparée avec patience pour un équilibre croustillant et moelleux.</p></article><article><b>02</b><h3>PRODUITS CHOISIS</h3><p>Qualité supérieure, aussi souvent que possible régionale, suisse et bio.</p></article><article><b>03</b><h3>TRADITION VIVANTE</h3><p>Tradition, innovation et éthique : notre façon de faire voyager Naples.</p></article></div></div></section>
   <section className="signature"><div className="sigImage"><img src="./images/foodtruck.png" alt="Food truck La Légende"/></div><div className="sigCopy"><span>NOTRE SIGNATURE</span><h2>LA LÉGENDE</h2><p>Sauce tomate, mozzarella, origan, roquette, tomates cerises, Grana Padano et jambon cru.</p><div className="price">DÈS <strong>CHF 13.–</strong></div><button className="textlink" onClick={()=>go('carte')}>DÉCOUVRIR LA CARTE <ArrowUpRight/></button></div></section>
   <section className="menuSec" id="carte"><div className="sectionNo">02 / LA CARTE</div><div className="menuHead"><h2>NAPOLI,<br/><i>À VOTRE PORTE.</i></h2><p>Des classiques intemporels aux créations de saison — avec des options végétariennes, véganes et sans lactose.</p></div><div className="menuFeature"><img src="./images/carte.png" alt="Carte complète des pizzas La Légende"/><div><span>LA CARTE DE LA TOURNÉE</span><h3>VOTRE PROCHAINE<br/>PIZZA EST ICI.</h3><p>Réservez par téléphone ou WhatsApp avant le service. Pendant le service, appelez-nous directement.</p><button className="order" onClick={()=>setOpen(true)}>Afficher la carte <ArrowUpRight/></button><small>Demandez aussi la Del Momento et la pizza de saison.</small></div></div></section>
   <section className="tour" id="tournee"><div className="sectionNo">03 / LA TOURNÉE</div><div className="tourHead"><h2>ON VIENT<br/><i>À VOUS.</i></h2><div><p><Clock/> Midi 11h30–12h45<br/><Clock/> Soir 18h15–20h00</p><span>Week-end sur réservation</span></div></div><div className="tourRows">{tour.map((r,i)=><a href={'tel:+41'+r[3].replace(/\s/g,'').slice(1)} className="tourRow" key={r[0]+r[1]}><span>{String(i+1).padStart(2,'0')}</span><b>{r[0]}</b><h3>{r[1]}</h3><p><MapPin/> {r[2]}</p><em>{r[3]} <ArrowUpRight/></em></a>)}</div></section>
   <section className="event" id="evenements"><img src="./images/trucks.jpg" alt="Les food trucks La Légende"/><div className="eventOverlay"><span>PRIVATISEZ LA LÉGENDE</span><h2>VOTRE ÉVÉNEMENT.<br/><i>NOTRE FOUR.</i></h2><p>Mariage, anniversaire, fête d’entreprise ou marché : offrez à vos invités une expérience rapide, généreuse et mémorable.</p><div className="eventTags"><span>Pizzas</span><span>Planches apéro</span><span>Bruschettas</span><span>Focaccias</span><span>Tiramisus</span></div><a className="order" href="mailto:info@pizzalegende.ch?subject=Demande%20de%20devis%20événement">Demander un devis <ArrowUpRight/></a></div></section>
   <section className="fresh" id="fraiches"><div><div className="sectionNo">04 / PIZZAS FRAÎCHES</div><h2>LA LÉGENDE,<br/><i>MÊME À LA MAISON.</i></h2><p>Nos pizzas fraîches sont préparées artisanalement dans le Jura bernois et disponibles au rayon frais de commerces partenaires en Suisse.</p><div className="shops">{shops.map(s=><span key={s}>{s}</span>)}</div><a className="textlink" href="mailto:info@pizzalegende.ch?subject=Distribution%20pizzas%20fraîches">DEVENIR REVENDEUR <ArrowUpRight/></a></div><img src="./images/fresh.png" alt="Pizzas fraîches artisanales"/></section>
   <section className="loyal"><div><span>CARTE FIDÉLITÉ 2026</span><h2>11 ACHETÉES.<br/><i>LA 12E OFFERTE.</i></h2></div><div><p>Simple, généreux, sans application. Valable sur la tournée pendant l’année en cours.</p><details><summary>Voir les conditions <ChevronDown/></summary><p>Une carte par personne et par commande. Non cumulable. Hors pizzas « De saison » et « Del Momento ». Rabais appliqué à la pizza la moins chère.</p></details></div></section>
   <section className="contest" id="concours"><span>CONCOURS EN COURS</span><h2>LA LÉGENDE<br/><i>X JOURNAL DU JURA</i></h2><p>À gagner : un bon d’une valeur de CHF 1’300.– pour une prestation événementielle privative avec le food truck, jusqu’à 40 personnes.</p><a className="ghost" href="https://www.pizzalegende.ch/concours" target="_blank">Règlement complet <ArrowUpRight/></a></section>
   <section className="contact"><p>UNE QUESTION, UNE COMMANDE,<br/>UN ÉVÉNEMENT ?</p><a href="tel:+41793691036">079 369 10 36 <ArrowUpRight/></a><a href="mailto:info@pizzalegende.ch">INFO@PIZZALEGENDE.CH <ArrowUpRight/></a></section>
  </main>
  <footer><div><img src="./images/logo.png"/><p>Food trucks & pizzas fraîches<br/>dans le Jura bernois.</p></div><div><b>NAVIGATION</b>{nav.map(([l,id])=><button key={id} onClick={()=>go(id)}>{l}</button>)}</div><div><b>SUIVEZ-NOUS</b><a href="https://www.instagram.com/" target="_blank"><Camera/> Instagram</a><a href="https://www.facebook.com/" target="_blank"><Users/> Facebook</a><a href="mailto:info@pizzalegende.ch"><Mail/> E-mail</a></div><div className="legal"><span>© 2019–2026 La Légende</span><a href="https://www.pizzalegende.ch/cgv">CGV</a><a href="https://www.pizzalegende.ch/declarationprotectiondonnees">Protection des données</a></div></footer>
  {open&&<div className="modal" onClick={()=>setOpen(false)}><button onClick={()=>setOpen(false)}><X/></button><img src="./images/carte.png" alt="Carte des pizzas" onClick={e=>e.stopPropagation()}/></div>}
 </>}
createRoot(document.getElementById('root')).render(<App/>);
